// what is javascript.
// Javascript is a server-side and client side scripting and object oriented
//language used to create web application and desktop application
// also used to create android app using JS library.

// Features.
// 1. Server side(backend) and client side(frontend) suppoertive.
// 2. Easily integrated with HTML-CSS
// 3. Dynamiclyy typed language.
// 4. Event-driven programming.
// 5. synchronous(sync) and asynchronous(async)
// 6. by default single threaded aznd also used as multithreaded.
// 7. top libraries : Reactjs, vuejs, angularjs, electronjs.

// Types of applying javascript:
// 1. Internal JS
// 2. External JS


var name1="IQ INDIA FROM DELHI" 
        // document.write(name1)
        // document.write("<hr>")
        // document.write("How are you")
console.log(name1)